[build]
    base = "web"
    command = "gatsby build"
    publish = "./public"
    functions = "./functions"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[dev]
    publish = "./public"
    autoLaunch = false
    port = 8888
    targetPort = 8000