[build]
    command = "gatsby build"
    publish = "./public"
    functions = "./functions"

[dev]
    publish = "./public"
    autoLaunch = false
    port = 8888
    targetPort = 8000

[context.deploy-preview]
  command = "npm run noIndex"

[context.branch-deploy]
  command = "npm run noIndex"