[build]
    base = "web"
    command = "gatsby clean && gatsby build"
    publish = "./public"
    functions = "./functions"

[dev]
    publish = "web/public"
    functions = "functions"
    functionsPort = 8008
    autoLaunch = false